# models/generator.py

"""
InstructModel Module.

This module defines the InstructModel class, which is used to interact with a language model
to generate instructions and process responses.
"""

import os
import json
import re
import torch
from typing import List, Dict, Optional
from transformers import AutoModelForCausalLM, AutoTokenizer
from config.config import *

class InstructModel:
    """
    Class to interact with an instructional language model.

    Attributes:
        model (AutoModelForCausalLM): The language model.
        tokenizer (AutoTokenizer): The tokenizer associated with the model.
        device (torch.device): The device (CPU or GPU) where the model is loaded.
    """

    def __init__(self) -> None:
        """
        Initializes the InstructModel class.
        """
        print("Loading the instruction generation model...")
        model_name = MODEL_GENERATOR_NAME
        if LOCAL_GENERATOR:
            model_path = os.path.join(os.getcwd(), LOCAL_FOLDER, model_name)
        else:
            model_path = model_name

        try:
            self.tokenizer = AutoTokenizer.from_pretrained(model_path)
            self.model = AutoModelForCausalLM.from_pretrained(model_path)
        except Exception as e:
            error_msg = f"while loading the model -> {e}"
            raise ValueError(error_msg)

        # Determine the device
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.model.to(self.device)
        print(f"Model loaded and moved to device: {self.device}")

    def _create_messages(self, task: str, input_text: str = "", output_text: str = "") -> List[Dict[str, str]]:
        """
        Creates messages based on the task and additional content.

        Args:
            task (str): The task name.
            input_text (str, optional): The input text. Defaults to "".
            output_text (str, optional): The output text. Defaults to "".

        Returns:
            List[Dict[str, str]]: A list of message dictionaries suitable for model input.

        Raises:
            ValueError: If the prompts file is not found or has invalid format, or if the task does not exist.
        """
        # Load the local JSON file defined by PROMPTS_FILE in config.py
        try:
            with open(PROMPTS_FILE, "r", encoding="utf-8") as file:
                prompts = json.load(file)
        except FileNotFoundError:
            error_msg = f"The JSON file '{PROMPTS_FILE}' was not found."
            
            raise ValueError(error_msg)
        except json.JSONDecodeError:
            error_msg = f"The JSON file '{PROMPTS_FILE}' has an invalid format."
            
            raise ValueError(error_msg)

        # Check if the task exists in the JSON file
        if task not in prompts:
            error_msg = f"The task '{task}' does not exist in the prompts JSON file (config/prompts.json)."
            raise ValueError(error_msg)

        # Get the context and instruction for the specific task
        context = prompts[task].get("context", "")
        instruction = prompts[task].get("instruction", "").format(input_text=input_text, output_text=output_text)

        # Build the message in the format expected by the model
        messages = [
            {"role": "system", "content": context},
            {"role": "user", "content": instruction},
        ]

        return messages

    def _extract_assistant_response(self, generated_text: str) -> Optional[str]:
        """
        Extracts the assistant's response from the generated text.

        Args:
            generated_text (str): The text generated by the model.

        Returns:
            Optional[str]: The assistant's response, or None if not found.
        """
        # If the result is a list, concatenate all elements into a single string
        if isinstance(generated_text, list):
            generated_text = " ".join(generated_text)

        # Use a regular expression to find the text that follows "assistant\n"
        match = re.search(r"assistant\n(.*)", generated_text, re.DOTALL)
        if match:
            return match.group(1).strip()
        return None

    def _get_response(self, messages: List[Dict[str, str]], num_return_sequences: int = 1, max_new_tokens: int = 200) -> List[Optional[str]]:
        """
        Generates responses from the model based on the provided messages.

        Args:
            messages (List[Dict[str, str]]): The messages to send to the model.
            num_return_sequences (int, optional): Number of responses to generate. Defaults to 1.
            max_new_tokens (int, optional): Maximum number of new tokens to generate. Defaults to 300.

        Returns:
            List[Optional[str]]: A list of the assistant's responses.
        """
        try:
            # Process the messages to convert them into text compatible with the model
            text = self.tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True
            )

            # Tokenize the input and convert it to PyTorch tensors
            model_inputs = self.tokenizer([text], return_tensors="pt").to(self.model.device)

            # Generate text using the model
            generated_ids = self.model.generate(
                **model_inputs,
                max_new_tokens=max_new_tokens,
                num_return_sequences=num_return_sequences,
                do_sample=True,
                pad_token_id=self.tokenizer.eos_token_id
            )

            # Decode the generated sequences from the generated IDs
            generated_texts = self.tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

            # Extract and process the assistant's specific responses
            responses = []
            for generated_text in generated_texts:
                response = self._extract_assistant_response(generated_text)
                responses.append(response)

            return responses
        except Exception as e:
            error_msg = f"response generation -> {e}"
            raise ValueError(error_msg)

    def generate(self, task: str, input_text: str = "", output_text: str = "", num_responses: int = 1) -> List[Optional[str]]:
        """
        Generates responses based on the task and additional instructions.

        Args:
            task (str): The task name.
            input_text (str, optional): The input text. Defaults to "".
            output_text (str, optional): The output text. Defaults to "".
            num_responses (int, optional): Number of responses to generate. Defaults to 1.

        Returns:
            List[Optional[str]]: A list of responses from the assistant.
        """
        try:
            messages = self._create_messages(task, input_text, output_text)
            responses = self._get_response(messages, num_responses)
            return responses
        except Exception as e:
            error_msg = f"generation -> {e}"
            raise ValueError(error_msg)
        
    @staticmethod
    def parse_generated_response(response: str) -> Dict[str, str]:
            """
            Parses the model's response to extract input-output pair.

            Args:
                response [str]: Response from the model.

            Returns:
                Dict[str, str]: Dictionary containing 'input' and 'output' keys.
            """
            parsed_response = {}

            for line in response.splitlines():
                line = line.strip()

                if "input" in line.lower() and ":" in line:
                    if 'input' in parsed_response and 'output' not in parsed_response:
                        parsed_response['output'] = ""
                        return parsed_response
                    
                    # Start a new pair with the new input
                    parsed_response['input'] = line.split(":", 1)[1].strip()

                elif "output" in line.lower() and ":" in line:
                    parsed_response['output'] = line.split(":", 1)[1].strip()

                if 'input' in parsed_response and 'output' in parsed_response:
                    return parsed_response
                
            return parsed_response